/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usersystem;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Diabj
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerpanel = new javax.swing.JPanel();
        fnameinput = new javax.swing.JTextField();
        registerbutton = new javax.swing.JButton();
        fnamelabel = new javax.swing.JLabel();
        rlogo = new javax.swing.JLabel();
        yellowpanel = new javax.swing.JPanel();
        registernowlabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mnamelabel = new javax.swing.JLabel();
        mnameinput = new javax.swing.JTextField();
        lnamelabel = new javax.swing.JLabel();
        lnameinput = new javax.swing.JTextField();
        emaillabel = new javax.swing.JLabel();
        emailinput = new javax.swing.JTextField();
        rusernameinput = new javax.swing.JTextField();
        rusernamelabel = new javax.swing.JLabel();
        rpasslabel = new javax.swing.JLabel();
        rpassinput = new javax.swing.JTextField();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerpanel.setBackground(new java.awt.Color(255, 255, 255));

        fnameinput.setOpaque(false);
        fnameinput.setSelectionColor(new java.awt.Color(255, 199, 28));
        fnameinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameinputActionPerformed(evt);
            }
        });

        registerbutton.setBackground(new java.awt.Color(255, 199, 28));
        registerbutton.setFont(new java.awt.Font("Verdana Pro Black", 1, 14)); // NOI18N
        registerbutton.setForeground(new java.awt.Color(46, 50, 60));
        registerbutton.setText("Register");
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });

        fnamelabel.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        fnamelabel.setForeground(new java.awt.Color(46, 50, 60));
        fnamelabel.setText("First Name");

        rlogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hi.png"))); // NOI18N
        rlogo.setText("jLabel7");

        yellowpanel.setBackground(new java.awt.Color(255, 204, 51));

        registernowlabel1.setFont(new java.awt.Font("Georgia Pro Cond Black", 0, 24)); // NOI18N
        registernowlabel1.setForeground(new java.awt.Color(46, 50, 60));
        registernowlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registernowlabel1.setText("Register now for a free account");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/register.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout yellowpanelLayout = new javax.swing.GroupLayout(yellowpanel);
        yellowpanel.setLayout(yellowpanelLayout);
        yellowpanelLayout.setHorizontalGroup(
            yellowpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yellowpanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registernowlabel1)
                .addGap(50, 50, 50))
        );
        yellowpanelLayout.setVerticalGroup(
            yellowpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yellowpanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(yellowpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registernowlabel1)
                    .addComponent(jLabel1))
                .addGap(19, 19, 19))
        );

        mnamelabel.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        mnamelabel.setForeground(new java.awt.Color(46, 50, 60));
        mnamelabel.setText("Middle name");

        mnameinput.setOpaque(false);
        mnameinput.setSelectionColor(new java.awt.Color(255, 199, 28));
        mnameinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameinputActionPerformed(evt);
            }
        });

        lnamelabel.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        lnamelabel.setForeground(new java.awt.Color(46, 50, 60));
        lnamelabel.setText("Last name");

        lnameinput.setOpaque(false);
        lnameinput.setSelectionColor(new java.awt.Color(255, 199, 28));
        lnameinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameinputActionPerformed(evt);
            }
        });

        emaillabel.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        emaillabel.setForeground(new java.awt.Color(46, 50, 60));
        emaillabel.setText("Email");

        emailinput.setOpaque(false);
        emailinput.setSelectionColor(new java.awt.Color(255, 199, 28));
        emailinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailinputActionPerformed(evt);
            }
        });

        rusernameinput.setOpaque(false);
        rusernameinput.setSelectionColor(new java.awt.Color(255, 199, 28));
        rusernameinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rusernameinputActionPerformed(evt);
            }
        });

        rusernamelabel.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        rusernamelabel.setForeground(new java.awt.Color(46, 50, 60));
        rusernamelabel.setText("Username");

        rpasslabel.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        rpasslabel.setForeground(new java.awt.Color(46, 50, 60));
        rpasslabel.setText("Password");

        rpassinput.setOpaque(false);
        rpassinput.setSelectionColor(new java.awt.Color(255, 199, 28));
        rpassinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpassinputActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(46, 50, 60));
        back.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back to Login");
        back.setBorderPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerpanelLayout = new javax.swing.GroupLayout(registerpanel);
        registerpanel.setLayout(registerpanelLayout);
        registerpanelLayout.setHorizontalGroup(
            registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yellowpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(registerpanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerpanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rusernameinput, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rpassinput, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rusernamelabel)
                                .addComponent(rpasslabel))))
                    .addComponent(rlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mnameinput)
                    .addComponent(lnameinput, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailinput, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fnamelabel)
                        .addComponent(emaillabel)
                        .addComponent(mnamelabel)
                        .addComponent(lnamelabel)
                        .addGroup(registerpanelLayout.createSequentialGroup()
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(registerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(fnameinput, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        registerpanelLayout.setVerticalGroup(
            registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerpanelLayout.createSequentialGroup()
                .addComponent(yellowpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerpanelLayout.createSequentialGroup()
                        .addComponent(fnamelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fnameinput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(mnamelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnameinput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(lnamelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnameinput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(emaillabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailinput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerpanelLayout.createSequentialGroup()
                        .addComponent(rusernamelabel)
                        .addGap(7, 7, 7)
                        .addComponent(rusernameinput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rpasslabel)
                        .addGap(7, 7, 7)
                        .addComponent(rpassinput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameinputActionPerformed

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        // TODO add your handling code here:
        String fname= fnameinput.getText();
        String mname= mnameinput.getText();
        String lname= lnameinput.getText();
        String email= emailinput.getText();
        String rusername= rusernameinput.getText();
        String rpass=rpassinput.getText();
        if(fname.isEmpty() || mname.isEmpty() || lname.isEmpty() || email.isEmpty() || rusername.isEmpty() || rpass.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please fill in the required fields","Incomplete",JOptionPane.ERROR_MESSAGE);
        } else{//login process
            userRegister(fname,mname,lname,email,rusername,rpass);
        }
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void mnameinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameinputActionPerformed

    private void lnameinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameinputActionPerformed

    private void emailinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailinputActionPerformed

    private void rusernameinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rusernameinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rusernameinputActionPerformed

    private void rpassinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpassinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rpassinputActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        dispose();
        login l = new login();
        l.setLocationRelativeTo(null);
        l.setVisible(true);
        l.setTitle("Login");
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField emailinput;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField fnameinput;
    private javax.swing.JLabel fnamelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lnameinput;
    private javax.swing.JLabel lnamelabel;
    private javax.swing.JTextField mnameinput;
    private javax.swing.JLabel mnamelabel;
    private javax.swing.JButton registerbutton;
    private javax.swing.JLabel registernowlabel1;
    private javax.swing.JPanel registerpanel;
    private javax.swing.JLabel rlogo;
    private javax.swing.JTextField rpassinput;
    private javax.swing.JLabel rpasslabel;
    private javax.swing.JTextField rusernameinput;
    private javax.swing.JLabel rusernamelabel;
    private javax.swing.JPanel yellowpanel;
    // End of variables declaration//GEN-END:variables

    private void userRegister(String fname, String mname, String lname, String email, String rusername, String rpass) {
        Connection dbconn = Connect.connectdb();
        if(dbconn != null){
        try {
            PreparedStatement st = (PreparedStatement)
                    dbconn.prepareStatement("INSERT INTO users (firstname,middlename,lastname,email,username,password) VALUES (?,?,?,?,?,?)");
            st.setString(1, fname);
            st.setString(2, mname);
            st.setString(3, lname);
            st.setString(4, email);
            st.setString(5, rusername);
            st.setString(6, rpass);
            int res = st.executeUpdate();
            JOptionPane.showMessageDialog(this,"User Data succesfully registered","Success",JOptionPane.INFORMATION_MESSAGE);
            fnameinput.setText("");
            mnameinput.setText("");
            lnameinput.setText("");
            emailinput.setText("");
            rusernameinput.setText("");
            rpassinput.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
            System.out.println("Connection unavailable");
        }
    }
}
